[build]
  command = "echo VITE_SUPABASE_URL=$VITE_SUPABASE_URL && echo VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY && vite build"
  publish = "dist/public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
